version: "3.8"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_10_drive_in_theater
      DB_USERNAME: root
      DB_PASSWORD: root
      L5_SWAGGER_GENERATE_ALWAYS: true

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    working_dir: /var/www/frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/var/www/frontend
    depends_on:
      - app

  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_10_drive_in_theater
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
      